baseURL = 'https://aben.be'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'aben'

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Filip Aben"
  github = "https://github.com/FilipAben"
  sitename = "aben"
  twitter = "@filipaben"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1